### PR TITLE
Feature hid integration

### PR DESCRIPTION
**Pull request by thenav56**

### CODE REVIEW

**Comment by thenav56** [comment]
@eoglethorpe , those logins are not sensitive. Those are only for dev testing for HID dev server. Any developer can create/modify those logins credentials.

Also, for this kind of credentials, it's better to just change the logins credentials instead of using bfg.

**Comment by thenav56** [comment]
Don't delete the branch. Will re-open the request on frontend addition.

**Review by frozenhelium — APPROVED** [review]

**Comment by bibekdahal** [comment]
```
Unhandled Rejection (TypeError): _rest.RestRequest.parseUrlParams is not a function
WrappedComponent.componentWillMount
src/topic/Authentication/views/Login/index.js:65
  62 | }
  63 | 
  64 | componentWillMount() {
> 65 |     const query = RestRequest.parseUrlParams(
  66 |         this.props.location.hash.replace('#', ''));
  67 |     const params = createParamsForTokenCreateHid(query);
  68 | 
```

My guess is the `react-store` repo is not up to date in its master branch, containing the above method in `RestRequest`. Let's defer the merging of this request till the react-store is updated.

**Comment by thenav56** [comment]
[PR Fix](https://gitlab.com/toggle-corp/react-store/merge_requests/15)

**Review by tnagorra — APPROVED** [review]

**Review by bibekdahal — APPROVED** [review]

**Pull request merged**
